"""Extract Input/Code cell expressions without cached output or cell metadata."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('250211_CavityIntegration.nb', '250211_IPAC_7.nb')


def input_cells(source):
    # Single lexical pass: delimiters inside strings/nested comments are inert.
    stack = []
    cells = []
    comment = 0
    quoted = False
    i = 0
    while i < len(source):
        pair = source[i:i+2]
        c = source[i]
        if comment:
            if pair == '(*':
                comment += 1
                i += 2
            elif pair == '*)':
                comment -= 1
                i += 2
            else:
                i += 1
            continue
        if quoted:
            if c == '\\':
                i += 2
                continue
            if c == '"':
                quoted = False
            i += 1
            continue
        if pair == '(*':
            comment = 1
            i += 2
            continue
        if c == '"':
            quoted = True
        elif c in '[{(':
            j = i
            while j and source[j-1].isspace():
                j -= 1
            end = j
            while j and (source[j-1].isalnum() or source[j-1] in '`$_'):
                j -= 1
            is_cell = c == '[' and source[j:end] == 'Cell'
            stack.append([c, i+1, [] if is_cell else None])
        elif c == ',' and stack and stack[-1][2] is not None:
            stack[-1][2].append(i)
        elif c in ']})':
            if not stack or stack[-1][0] != {']':'[','}':'{',')':'('}[c]:
                raise ValueError(f'Unbalanced delimiter at {i}')
            _, start, commas = stack.pop()
            if commas:
                stop = commas[1] if len(commas) > 1 else i
                style = source[commas[0]+1:stop].strip()
                if style in ('"Input"', '"Code"'):
                    cells.append((start, 'Cell[' + source[start:commas[0]] + ', ' + style + ']'))
        i += 1
    if stack or quoted or comment:
        raise ValueError('Unterminated expression')
    return [cell for _, cell in sorted(cells)]


def render(source):
    cells = input_cells(source)
    if not cells:
        raise ValueError('No input cells found')
    notice = 'Cell["Input-only archival reading copy. Review paths and settings before evaluation; fresh kernel execution is not validated.", "Text"]'
    return '(* Generated by tools/extract_notebook_inputs.py; originals are preserved. *)\nNotebook[{\n' + ',\n\n'.join([notice] + cells) + '\n}]\n', len(cells)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    # Exercise nested cells, strings, escaped quotes and nested comments.
    sample = 'Notebook[{Cell[CellGroupData[{Cell[BoxData["a,]\\\""], "Input", X->1],Cell[BoxData["x"], "Output"]}]],(* a (* b *) *)Cell["x", "Code"]}]'
    assert len(input_cells(sample)) == 2
    for name in NAMES:
        content, count = render((ROOT / 'research/Mathematica' / name).read_text())
        target = ROOT / 'notebooks' / name
        if args.check:
            assert target.read_text() == content, f'Stale extraction: {target}'
        else:
            target.parent.mkdir(exist_ok=True)
            target.write_text(content)
        assert len(input_cells(content)) == count
        print(f'{name}: {count} input/code cells, {len(content.encode())} bytes')


if __name__ == '__main__':
    main()
